from PyQt5 import QtCore, QtGui, QtWidgets
from instr import Ui_Instrucciones
import icons_rc

class Ui_CinemaSimi(object):

    def openInstrucciones(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Instrucciones()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, CinemaSimi):
        CinemaSimi.setObjectName("CinemaSimi")
        CinemaSimi.setWindowModality(QtCore.Qt.NonModal)
        CinemaSimi.resize(1080, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CinemaSimi.sizePolicy().hasHeightForWidth())
        CinemaSimi.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/recursos/upc_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        CinemaSimi.setWindowIcon(icon)
        CinemaSimi.setAutoFillBackground(False)
        CinemaSimi.setStyleSheet("background-color: rgb(255, 234, 212);")
        CinemaSimi.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        CinemaSimi.setTabShape(QtWidgets.QTabWidget.Rounded)

        self.centralwidget = QtWidgets.QWidget(CinemaSimi)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget3.setMaximumSize(QtCore.QSize(650, 230))
        self.gridWidget3.setObjectName("gridWidget3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridWidget3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblLogo = QtWidgets.QLabel(self.gridWidget3)
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/icons/recursos/cinemaSimi.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setObjectName("lblLogo")
        self.gridLayout_2.addWidget(self.lblLogo, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gridWidget3, 0, 1, 1, 1)
        self.gridWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget4.setMaximumSize(QtCore.QSize(650, 450))
        self.gridWidget4.setObjectName("gridWidget4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridWidget4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnAdd = QtWidgets.QToolButton(self.gridWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAdd.sizePolicy().hasHeightForWidth())
        self.btnAdd.setSizePolicy(sizePolicy)
        self.btnAdd.setMaximumSize(QtCore.QSize(260, 260))
        self.btnAdd.setSizeIncrement(QtCore.QSize(2, 2))
        self.btnAdd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/recursos/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon1)
        self.btnAdd.setIconSize(QtCore.QSize(250, 250))
        self.btnAdd.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnAdd.setAutoRaise(True)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout_4.addWidget(self.btnAdd, 0, 0, 1, 1)
        self.lblNuevoProyecto = QtWidgets.QLabel(self.gridWidget4)
        self.lblNuevoProyecto.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNuevoProyecto.sizePolicy().hasHeightForWidth())
        self.lblNuevoProyecto.setSizePolicy(sizePolicy)
        self.lblNuevoProyecto.setMaximumSize(QtCore.QSize(270, 40))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.lblNuevoProyecto.setFont(font)
        self.lblNuevoProyecto.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lblNuevoProyecto.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblNuevoProyecto.setObjectName("lblNuevoProyecto")
        self.gridLayout_4.addWidget(self.lblNuevoProyecto, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gridWidget4, 1, 1, 1, 1)
        self.gridWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget1.setMaximumSize(QtCore.QSize(180, 180))
        self.gridWidget1.setObjectName("gridWidget1")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridWidget1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btnQuestion = QtWidgets.QToolButton(self.gridWidget1, clicked= lambda: self.openInstrucciones() )
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnQuestion.sizePolicy().hasHeightForWidth())
        self.btnQuestion.setSizePolicy(sizePolicy)
        self.btnQuestion.setMaximumSize(QtCore.QSize(110, 110))
        self.btnQuestion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/recursos/question_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnQuestion.setIcon(icon2)
        self.btnQuestion.setIconSize(QtCore.QSize(80, 80))
        self.btnQuestion.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btnQuestion.setAutoRaise(True)
        self.btnQuestion.setObjectName("btnQuestion")
        self.gridLayout_9.addWidget(self.btnQuestion, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gridWidget1, 0, 0, 1, 1)
        self.gridWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget2.setMinimumSize(QtCore.QSize(0, 0))
        self.gridWidget2.setMaximumSize(QtCore.QSize(180, 180))
        self.gridWidget2.setBaseSize(QtCore.QSize(140, 140))
        self.gridWidget2.setObjectName("gridWidget2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridWidget2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label = QtWidgets.QLabel(self.gridWidget2)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/recursos/upc_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.gridWidget2, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_7.addItem(spacerItem, 2, 1, 1, 1)
        CinemaSimi.setCentralWidget(self.centralwidget)

        self.retranslateUi(CinemaSimi)
        QtCore.QMetaObject.connectSlotsByName(CinemaSimi)

    def retranslateUi(self, CinemaSimi):
        _translate = QtCore.QCoreApplication.translate
        CinemaSimi.setWindowTitle(_translate("CinemaSimi", "CinemaSimi"))
        self.btnAdd.setText(_translate("CinemaSimi", "..."))
        self.lblNuevoProyecto.setText(_translate("CinemaSimi", "<html><head/><body><p align=\"center\">  Crear nuevo proyecto</p></body></html>"))
        self.btnQuestion.setText(_translate("CinemaSimi", "..."))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CinemaSimi = QtWidgets.QMainWindow()
    ui = Ui_CinemaSimi()
    ui.setupUi(CinemaSimi)
    CinemaSimi.show()
    sys.exit(app.exec_())
